---

dist: xenial
language: minimal
git:
  depth: 5

#

.env:
  github_keys: &github_keys
    - secure: "lzUEmh8QBQhrHvwbFgn3hYbzcCqbN2dg6gymyKPO9TAKdXFOrUetHiZwjt5sww0dtALNw1qcb/JeHPnrmuLTd7V0Pf/zTcFXv9upKC5XVBwJbFfR9cAhBHxY4QNzuy8cV2qGahuoiloOTOyj3xyBZT8Id78fwqqeyldaPBT/X0DHJmrGZQ6AgqKIRQwJ5aZ5rEqXBbNYB9UKGPzRpF4HoFJxUbJcLk6/3NA6IlR44USO9UCdAQ6s+DCb6MzcqDy2wwnL40XMtbsjFY/EMW0EF6Ey7dVyzukFPr6yxq12pTqxLBtsi+NsxIEtfoB4l+wn+fmcMo3t/gUUAinYCZMm/YC6Bm4zMwYiTWQoKBQI6Chf/7azsvKABHjmRdTPo6JcO2u8u2PKsBKD9T2avPr2ByRPakxSWRxjspHbmd8GGcRRWp8rTBztEf3Jiltmr2d7qilwpy/r7RcmvOClMAdcmsJfP66J8X8sRRRQhuApLo0g/IWxrdUP83dmHzDARAIJMwEKsd06w0QncMjCOIw69G5eQByzU233r4FqLry8gWxMbHc0Znpn9fycrjybB2UAV7QCdUzb/Sm/6jWglXR3b8pWyPADr4amPO59zvYGBQmP0ZGD1aHBiZaEg10T+kkc4zw1OZPcRvYJpb0vS81vRU+QXjBQGMp2pSLSDGKXzk8="

#

.node_stage: &node_stage
  language: node_js
  node_js: "10"
  cache: yarn
  before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
  install:
    - yarn --frozen-lockfile

#

jobs:
  include:
    - stage: Build
      <<: *node_stage
      if: NOT env(RELEASE)
      env: *npm_keys
      script:
        - yarn build
        - yarn lint
        - yarn test --coverage
      after_success:
        - npx codecov
      deploy:
        provider: npm
        #
        api_key: "$NPM_TOKEN"
        email: "$NPM_EMAIL"
        skip_cleanup: true
        on:
          tags: true

    - stage: Release
      <<: *node_stage
      if: env(RELEASE)
      name: Make a new release 🎉
      git:
        # NOTE(douglasduteil): disable git --depth
        # Try to have all the commits for the release Change Log
        # see travis-ci/travis-ci#3412
        depth: 9999999 # Over 9000 !
      env: *github_keys
      install:
        - yarn global add semantic-release @semantic-release/changelog @semantic-release/git
      before_script:
        - git checkout ${TRAVIS_BRANCH}
        - git config user.name "Social Groovy Bot"
        - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
      script:
        - semantic-release
