name: Demo

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Yarn cache setup
        uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Build demo
        run: yarn build:demo

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages
          folder: example/dist
